<?php

/*************************************************************************************
 *
 * AIM: Class to perform User Add, Password Update in Mail Server
 * Author: MD Danish <trade.danish@gmail.com>
 * Date Written: June 14, 2016
 *
 ************************************************************************************/


class oneidnet_rc { 

	private $connection;
	function index(){
		}
	//Function to return the password hash from python library
	function getPasswordHash( $plain_text_password , $salt ) {
		$passwordHash = passthru ("python passwordLibrary.py $plain_text_password $salt"); 
		if( $passwordHash != 'ERROR' ) {
			return $passwordHash;
		} else {
			return false;
		}
	}
	
	// This is equivalent function to generate the same password-hash as generated by python class
	function comparePasswordHash( $plain_text_password , $salt ) {
		$status = "{SSHA512}".base64_encode(hash('sha512', $plain_text_password.$salt, true).$salt);		
	}
	
	function updatePasswordHashInOneidnet (  ) {
		$password = $this->getPasswordHash( $plain_text_password , $salt );
	}
	
	//Function To Handle MySqli Connection Error & Log Them
	function errorLogComposer( $error_code, $type ){
		$time_str = date('M h, Y H:i:s A(e)');
		$logString = "{$time_str}:: {$type}: {$error_code} \n";	
		$file = fopen('log.txt','a');
		fwrite( $file , $logString );
		fclose($file);
	}
	
	// Function to initiate database connection ...
	function db_connect( $params ) {		
		 $connection = mysqli_connect( $params['HOST'] , $params['USER'], $params['PASSWORD'], $params['DATABASE'] ) or $this->errorLogComposer( mysqli_connect_errno($connection),"DB CONNECTION ERROR" );
		if($connection){
			 echo 'connection';
			// exit();
			return $connection;
		} else {
			 echo 'no connection';
			// exit();
			return false; // Unable to Create Connection String			
		}
	}
	
	// Shorthand Function to perform DB Queries,
	// Possible Value Of $crud_type = Select | Insert | Update | Delete 
	function execute_query( $query, $connections_params, $crud_type ) {		
		$this->connection = $this->db_connect( $connections_params );
		if( !$this->connection ) {
			$this->errorLogComposer( mysqli_connect_errno($this->connection),"DB CONNECTION ERROR" );
			return false; // Means Connection Error
		} else {
			$result = mysqli_query( $this->connection, $query );
			$affected_result = mysqli_affected_rows( $this->connection );
			echo var_dump($affected_result);
				if( $affected_result ) {
					if( strtolower($crud_type) == 'insert'  ) {
						echo $crud_type;
						while( $row=mysqli_fetch_assoc($result) ) {
							$data[] = $row;
						}										
					} else {
						echo 'no insert type';
						return true;
					}										
				} else {
					return false;					
				}	
		}	// End Of Main If Loop	
	}
	
	function db_commit(  ) {
		return mysqli_commit($this->connection);		
	}
	
	function db_rollback(  ) {
		return mysqli_rollback($this->connection);		
	}

	
	/* Function to add the Mailbox and Alias in Mail Server 
	 * $host = 'oneidnet.com'
	 * $username = 'danish'
	 * $password_hash <Standard Value returned using getPasswordHash() function>
	 * Usage Example: $bd = $b->addMailbox( $username='sarina1', $full_name='Sarina Almas', $password_hash='{SSHA512}VVHb9aVMTJ+gsiCx2mbTlWp1AIlwoiRfaFG9HS+ZJPElJKcquIw7by9d2U2tah+7tQRhZi2YuWzvjj2rw2hGHWFiYw==', $quota_in_mb=1024 ) ;
	 */
	 
	function addMailbox( $username, $full_name, $password_hash, $quota_in_mb ) {
		date_default_timezone_set('Asia/Kolkata'); // Default Server Timezon must be explicitly defined
		
		$domain = "oneidnet.com"; //Don't Change this 
		
		$dbConnections_params = array(
			'HOST'=>'mail.oneidnet.com',
			'USER'=>'oneid108',
			'PASSWORD'=>'password',
			'DATABASE'=>'vmail'
		);
		// $this->db_connect($dbConnections_params);
		// exit();
		 $email = $username."@".$domain;
		$storage_node = $domain."/".substr($username, 0, 1)."/".substr($username, 1, 1)."/".substr($username, 2, 1)."/".$username."-"
						.date('Y').".".date('m').".".date('d').".".date('h').".".date('i').".".date('s')."/";
		  $mailbox_query = "INSERT INTO mailbox (username, password, name, language, storagebasedirectory,storagenode, maildir, quota, domain, active, created)".
             "VALUES ('{$email}', '{$password_hash}', '{$full_name}','en_US',
                     '/var/vmail','vmail1', '{$storage_node}', '{$quota_in_mb}', '{$domain}', '1', NOW())";
        
        $alias_query = "INSERT INTO alias (address, name, domain, created, active) VALUES ('{$email}', '{$full_name}','{$domain}', NOW(), 1)";
    	$mailbox_response_flag1 = $this->execute_query( $mailbox_query, $dbConnections_params,$crud_type="insert" );
		$mailbox_response_flag2 = $this->execute_query( $alias_query, $dbConnections_params, $crud_type="insert" );	
		if($mailbox_response_flag1 && $mailbox_response_flag2 ) {			
		
			return $this->db_commit() ? "MAILBOX_ADDED_SUCCESSFULLY" : "MAILBOX_ADDED_SUCCESSFULLY_BUT_COMIT_FAILED";			
		} else {
			// Either or All query Failed, Call to Rollback Action
			return $this->db_rollback() ? "OPERATION_UNCOMPLETE" : "ROLLBACK_FAILED";
		}		
		
	}
	
	// Function to Change the Mail Box Password
	// Usage: $b->changeMailboxPassword( $username='sarina1', $password_hash='{SSHA512}VVHb9aVMTJ+gsiCx2mbTlWp1AIlwoiRfaFG9HS+ZJPElJKcquIw7by9d2U2tah+7tQRhZi2YuWzvjj2rw2hGHWFiYw==' );
	function changeMailboxPassword( $username, $password_hash ){
		$email = $username.'@oneidnet.com';
		$dbConnections_params = array(
			'HOST'=>'192.168.22.14',
			'USER'=>'oneidnetmSuper',
			'PASSWORD'=>'OneidnetMailsNations786@India',
			'DATABASE'=>'vmail'
		);
		 $query = "UPDATE mailbox SET password='{$password_hash}' where username='{$email}'";
		 $flag = $this->execute_query( $query, $dbConnections_params,$crud_type="update" );
		if( $flag ) {
                    
			return $this->db_commit() ? "PASSWORD_CHANGED_SUCCESSFULLY" : "PASSWORD_CHANGED_SUCCESSFULLY_BUT_COMIT_FAILED";
		} else {
			return false;
		}
	}
}

//Class Initiation
//$oneidnetRCobj = new oneidnet_rc(  );
//echo $oneidnetRCobj->changeMailboxPassword( $username='sarina90', $password_hash='shiva');
//$bd = $oneidnetRCobj->addMailbox( $username='sarina90', $full_name='Sarina Almas 90', $password_hash='{SSHA512}VV9aVMTJ+gsiCx2mbTlWp1AIlwoiRfaFG9HS+ZJPElJKcquIw7by9d2U2tah+7tQRhZi2YuWzvjj2rw2hGHWFiYw==', $quota_in_mb=1024 ) ;
?>
